version: '3.8'
services:
  redis:
    image: registry.cn-guangzhou.aliyuncs.com/kubernetes-default/redis:6.0.20
    depends_on:
      - clearflask-server
    ports:
      - 6379:6379
    command: 
      - 'redis-server'
      - '/etc/redis/redis.conf'
    volumes:
      - ./data:/data
      - ./redis:/etc/redis/redis.conf