apiVersion: v1
kind: Service
metadata:
  labels:
    victoriametrics: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: victoriametrics-kube-dns
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
---
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/coredns.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-coredns
  namespace: monitor
  labels: 
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/version: "v1.101.0"
spec:
  selector:
    matchLabels:
      victoriametrics: kube-dns
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: metrics
  jobLabel: app.kubernetes.io/name
