# etcd-k8s-services.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  clusterIP: None # 一定要设置 clusterIP:None
  # selector:
  #   component: etcd
  ports:
    - name: port
      port: 2381
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
  - addresses:
      - ip: 172.16.10.101 # 指定etcd节点地址（通常是master地址），如果是集群则继续向下添加
        nodeName: etcd-master
    ports:
      - name: port
        port: 2381
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: etcd-k8s
  namespace: monitor
  labels:
    k8s-app: etcd-k8s
spec:
  jobLabel: kubeSystemEtcd
# Etcd 的入口
  podMetricsEndpoints:
    - port: port
      targetPort: 2381
      interval: 15s
# 这里非常重要，匹配 Pod 的标签
  selector:
    matchLabels:
      component: etcd
# 指定 Pod 所在 Namespace
  namespaceSelector:
    matchNames:
      - kube-system