---
# Source: victoria-metrics-k8s-stack/templates/servicemonitors/nodeexporter.yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-metrics-node-exporter
  namespace: monitor
  labels: 
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/instance: vm-operator
    app.kubernetes.io/version: "v1.101.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  endpoints:
  - metricRelabelConfigs:
    - action: drop
      regex: /var/lib/kubelet/pods.+
      source_labels:
      - mountpoint
    port: metrics
  jobLabel: jobLabel