---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  labels:
    app: pushprox-client
  name: sre-test
  namespace: monitor
spec:
  jobName: sre-test
  targetEndpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 60s
      scrapeTimeout: 10s
      labels:
        type: local
        host: sre-test
      targets:
        - http://${HOST}:9182
