apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria-metrics
  namespace: monitor
spec:
  retentionPeriod: "90d"
  removePvcAfterDelete: true
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.93.15
  storage:
    storageClassName: default
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  extraArgs:
    dedup.minScrapeInterval: 60s
    search.disableAutoCacheReset: "true"
  affinity: {}
  tolerations:
    - key: ack-pool-name
      value: prod
      effect: NoSchedule
      operator: Equal
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 6Gi
      cpu: 4
