apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: main
  namespace: monitor
spec:
  username: isadmin
  password: isadmin
  targetRefs:
    - crd:
        kind: VMAlertmanager
        name: main
        namespace: monitor
      paths:
        - "/alertmanager/.*"
    - static:
        url: "http://vmalert-main:8080"
      paths:
        - "/vmalert/.*"
        - "/api/v1/.*"
    - static:
        url: "http://vmagent-main:8429"
      paths:
        - "/api/v1/targets"
        - "/static/.*"
        - "/service-discovery"
        - "/targets"
        - "/targets/.*"
        - "/config"
        - "/target-relabel-debug"
        - "/metrics"
    - crd:
        kind: VMSingle
        name: victoria-metrics
        namespace: monitor
      paths:
        - "/vmui/.*"
        - "/prometheus/api/.*"
        - "/api/v1/.*"
