modules:
  http_2xx:
    http:
      # 指定的协议
      preferred_ip_protocol: ip4
      # 若 HTTP 版本不在字段指定的范围内，则探测失败
      valid_http_versions: [HTTP/1.1, HTTP/2]
      # 此探针可以接受的响应状态码。默认值：2xx。注:2xx 表示所有 2xx 状态码，这个字段的值如果要手动指定，必须是 int 类型。若响应码不在该字段指定的范围内，则探测失败
      valid_status_codes: [200, 301, 302, 308, 401, 403, 404, 405]
      # 请求方法
      method: GET
      # 是否开启跟随跳转
      follow_redirects: false
    prober: http
    timeout: 8s
  http_post_2xx: # POST 请求检测服务器存活
    http:
      method: POST
      preferred_ip_protocol: ip4
      valid_status_codes: [200, 301, 302, 308, 401, 403, 404, 405]
    prober: http
    timeout: 8s
  tcp_connect: # tcp 连接
    prober: tcp
    timeout: 8s
    tcp:
      preferred_ip_protocol: ip4
  icmp: # ping 检测服务器的存活
    prober: icmp
    timeout: 2s
    icmp:
      preferred_ip_protocol: "ip4" # 默认是 ip6
