- name: Install Docker on Debian
  remote_user: isadmin # Change remote user to your sudo user!
  become: true
  hosts:
    - test
  roles:
    - docker
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
